# Site settings
title: Про Swift. Українською # site title
description: >- # site description
  swift.org.ua – це спільнота для обміну інженерним досвідом. Тут можна знайти книгу про Swift українською: <a href="https://book.swift.org.ua/" target="_blank">book.swift.org.ua/</a>
lang: uk_UA # default lang
timezone: Europe/Kyiv # set your timezone
image: /assets/img/swift_logo.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/swiftbookua/site # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings  
author:
  name: Славік Володько # author name
  bio: >- # tell to the world
    Вітаю! Я <a href="http://facebook.com/killobatt" target="_blank">Славік Володько</a>, займаюсь iOS-розробкою з 2011, 
    нині працюю в <a href="http://grammarly.com/" target="_blank">Grammarly</a>. Хтось міг мене бачити на CocoaHeads Ukraine. 
    Також я переклав книгу "The Swift Programming Language" українською: <a href="https://book.swift.org.ua/" target="_blank">book.swift.org.ua/</a>.
  username: killobatt # general username
  github: killobatt # github username
  twitter: killobatt # twitter username
  facebook: killobatt # facebook username
  email: killobatt@gmail.com # email adress
  avatar: /assets/img/swift_logo.png # change with your own avatar

# URL settings
url: "https://swift.org.ua" #
baseurl:
permalink: /:title/
google_analytics: UA-36462206-4 # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 20

# Build settings
# theme: klise
sass:
  style: compressed

# mermaid:
#   custom: https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
  - jekyll-mermaid
